@startuml

left to right direction
skinparam packageStyle rectangle

actor Player1
actor Player2

rectangle Game {
    Player1 --> (Start Game)
    Player1 --> (Take Turn)
    Player2 ---> (Take Turn)
    Player1 ---> (End Game)
    Player2 ---> (End Game)
    (Take Turn) .> (Roll Dice) : <<include>>
    (Take Turn) ..> (Move To Field) : <<include>>
    (Take Turn) ..> (Output Message) : <<include>>
    (Take Turn) ..> (Change Balance) : <<extend>>
    (Change Balance) ..> (Withdraw Money) : <<extend>>
    (Change Balance) ..> (Deposit Money) : <<extend>>
}
@enduml