@startuml
'https://plantuml.com/sequence-diagram

'autonumber

Participant MatadorMain
Participant GameController <<Singleton>>
Participant ViewController <<Singleton>>


MatadorMain -> GameController : getInstance()
MatadorMain -> GameController : initializeGame()

GameController -> ViewController : getInstance()

GameController -> ViewController : setupGUIBoard()
GameController -> ViewController : getPlayerNames()
ViewController --> GameController : playerNames

create Player

GameController --> Player : «create»

create Account

Player --> Account : «create»

create DiceCup

GameController --> DiceCup : «create»

create Board

GameController --> Board : «create»

create FieldsCreator <<Service>>

Board --> FieldsCreator : «create»

create Fields

FieldsCreator --> Fields : «create»


GameController -> ViewController : putPlayersOnBoard()

MatadorMain -> GameController : gameLoop()

GameController -> GameController : takeTurn()


@enduml
