@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor   Game.Player
mainframe Take a turn

Game.Player -> DiceGame: Play()
DiceGame -> Game.Player: getCurrentPlayer()
Game.Player -> DiceCup: roll()
DiceCup -> Game.Die: roll()
Game.Die -> DiceCup: getFaceValue()
DiceCup -> DiceGame: getSum()
DiceGame -> Game.Field: getFieldEffect()
Game.Field --> DiceGame: done
DiceGame -> Game.Account: updateBalance()
Game.Account --> DiceGame: done

@enduml