@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor   Player
mainframe Take a turn

Player -> DiceGame: Play()
DiceGame -> Player: getCurrentPlayer()
Player -> Die: roll()
DiceGame -> Die: getFaceValue()
DiceGame -> Field: landOnField()

Field --> DiceGame: done
DiceGame -> Account: updateBalance()
Account --> DiceGame: done

@enduml