@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

class MonopolyGame {

}

class Player {

}

class Board {

}

class Field {

}

class Account {

}

class Die {

}

class ChanceCard {

}

class StartField {

}

class AmusementField {

}

class ChanceField {

}

class Jail {

}

class FreeParking {

}

class VisitJail {

}

MonopolyGame -- Board
MonopolyGame -- Die
MonopolyGame -- Player
Player -- Account
Board -- Field
Field <|-- StartField
Field <|-- AmusementField
Field <|-- ChanceField
Field <|-- Jail
Field <|-- FreeParking
Field <|-- VisitJail
ChanceCard - ChanceField


@enduml