@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Game.Player

System -> Game.Player: Welcome message
Game.Player -> System: Initialize game
Game.Player -> System: Play game

loop No winner
    System --> Game.Player: Game.Die value, field acount, chance card
end

System -> Game.Player: Output winner

@enduml