@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Player

System -> Player: Welcome message
Player -> System: Initialize game
Player -> System: Play game

loop No winner
    System --> Player: Die value, field acount, chance card
end

System -> Player: Output winner

@enduml