@startuml
'https://plantuml.com/use-case-diagram

left to right direction

actor player

rectangle MonopolyJr {
    usecase "Set up board and players" as uc1

    usecase "Take turn" as uc2
    usecase "Rolle die" as uc2.1
    usecase "Move piece" as uc2.2
    usecase "Draw Chance Card" as uc2.3
    usecase "Go to jail" as uc2.4
    usecase "set up booth" as uc2.5
    usecase "Pass start field" as uc2.6

    usecase "Win game" as uc3
}

player --> uc1

player --> uc2
uc2 ..> uc2.1 : include
uc2 ..> uc2.2 : include
uc2 <.. uc2.3 : extend
uc2 <.. uc2.4 : extend
uc2 <.. uc2.5 : extend
uc2 <.. uc2.6 : extend

player --> uc3

@enduml