@startuml
'https://plantuml.com/state-diagram

scale 350 width
[*] --> Start
Start: Bondemand, ræv, gås & korn på side 1.

Start --> gås: gås flyttes
gås: Bondemand og gås på side 2. ræv og korn på side 1.

gås --> ræv: ræv flyttes
ræv: ræv, gås og bondemand side 2. Korn side 1.

ræv -> gåsTilbage: gås flyttes tilbage
gåsTilbage: ræv side 2, bondemand, gås og korn side 1.

gåsTilbage -> korn: korn flyttes
korn: ræv, korn og bondemand side 2, gås side 1.



@enduml