@startuml
'https://plantuml.com/state-diagram

scale 350 width
[*] --> Login: user logs in
Login: Login screen shown

Login --> Inbox: User opens inbox
Inbox: Inbox is shown

Inbox --> Message: User opens message
Message: Message is shown

Login --> Outbox: User opens outbox
Outbox: Outbox is shown

Outbox --> NewMessage: User creates new message
NewMessage: New message window shown

NewMessage --> SentMessage: User sends new message
SentMessage: Sent message window shown



@enduml