@startuml
'https://plantuml.com/sequence-diagram

'autonumber

create MatadorMain
create GameController <<Singleton>>

MatadorMain --> GameController : «create»
MatadorMain -> GameController : initializeGame()

create ViewController <<Singleton>>

GameController --> ViewController : «create»

GameController -> ViewController : setupGUIBoard()
GameController -> ViewController : getPlayerNames()
ViewController --> GameController : playerNames

create Player

GameController --> Player : «create»

create Account

Player --> Account : «create»

create Board

GameController --> Board : «create»

create DiceCup

GameController --> DiceCup : «create»

GameController -> ViewController : putPlayersOnBoard()

GameController -> GameController : playerTurn()

@enduml
