@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

object Matador {

}

object Player {
    name
    isBankrupt
}

object Board {

}

object Field {
    name
}

object Account {
    balance
}

object DiceCup {

}

object Die {
    facevalue

}

object ChanceCard {
    text
}

Matador -- Board
Matador -- DiceCup
Matador "1" -- "3..6" Player
Player -- Account
Board "1" -- "40" Field
ChanceCard "*" - "1" Matador
DiceCup "1" -- "2" Die



@enduml