@startuml
'https://plantuml.com/use-case-diagram

left to right direction

actor player

rectangle Matador {
    usecase "Setup game" as uc1

    usecase "Take turn" as uc2

}

player --> uc1

player --> uc2



@enduml